### ISSUE TITLE
Ignore urls

### ISSUE THREAD

**Issue by rubyAnneB** [rjayroso/haystack-link-checker#15]
I'd like to work on your repo to add a feature that allows the user to specify URLs to be ignored in a text file that would then be read by haystack to determine which links to not check.

**Comment by rjayroso** [comment]
Go for it!

**Comment by rubyAnneB** [comment]
For remote
Ruby Anne- https://github.com/rubyAnneB/haystack-link-checker.git

**Comment by rjayroso** [comment]
Thanks, I'll take a look

**Comment by rjayroso** [comment]
Closed via commit d567080
